### ISSUE TITLE
☂️ Features useful/needed for storj/common and storj/storj

### ISSUE THREAD

**Issue by egonelbre** [storj/picobuf#23]
This tracks a list of issues that need solving for switching from gogo to storj.io/common:

```[tasklist]
### Tasks
- [ ] https://github.com/storj/drpc/issues/53
- [ ] https://github.com/storj/picobuf/issues/25
- [ ] https://github.com/storj/picobuf/issues/26
- [ ] https://github.com/storj/picobuf/issues/27
- [ ] check performance against gogo and standard google protobuf
- [ ] https://github.com/storj/picobuf/issues/28
```
